### PR TITLE
Fix authentication and faster startup when data is recent

### LINKED ISSUE #235: Won’t login bitstamp
I filled everything (usercode, key and secret) and it still wont log in. 

Question:
After you start bitvision you get immediately all the stats/charts? Or is that after you after login? 

I ask this because maybe the terminal/npm wont allow connection at all.

### PR DESCRIPTION
**Pull request by chrkaatz**
Fixes #235

Speeds up the startup, when there is already recent data available, use momentjs for date formatting

### CODE REVIEW

**Comment by alichtman** [comment]
If you remove all `store/*` files to minimize the diff, that'd be dope. Maybe add those to the .gitignore and commit that.

**Comment by alichtman** [comment]
Auth fix looks good to me, and the data fetching optimization, too. Should close #235.

Note: I have not tested this.

@shobrook ?

**Comment by chrkaatz** [comment]
@alichtman Sorry, was not on the computer. I verified that it could pick up my recent transactions. But did not verify trading yet

**Comment by alichtman** [comment]
If you could test that out and let me know, that'd be great. I don't have a lot of free time to work on this for a bit.

**Comment by shobrook** [comment]
Great improvements! I reverted your changes to the colorize function, since you were pulling the wrong item from `row`. I also reverted the change to the transaction window size, just to keep the UI looking organized. Other than that, everything looked solid!

**Pull request merged**
